/*
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.SFMCLocationController;
const CreateLocationRequest = testerlib.CreateLocationRequest;

describe("SFMCLocationController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * TODO: Add Description
     */
    it("should testRetrieveAllLocations response", function testRetrieveAllLocationsTest(done) {
        // parameters for the API call
        let contentType = 'application/json';

        controller.retrieveAllLocations(contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * Enable create location
     */
    it("should testCreateLocation response", function testCreateLocationTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let body = baseController.getObjectMapper().mapObject({"name": "PINTS Brewing", "location": "412 NW 5th Ave Portland, OR 97209", "description": "PINTS Brewing", "center": {"latitude": 45.526176, "longitude": -122.675498}, "radius": 50, "attributes": [{"attribute": "Address 1", "value": "412 NW 5th Ave"}, {"attribute": "City", "value": "Portland"}, {"attribute": "State", "value": "OR"}, {"attribute": "Zip", "value": "97209"}]}, 'CreateLocationRequest');

        controller.createLocation(contentType, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });
});
