/*
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.SFMCMessagingController;
const MessageDefinitionSendEmailRequest = testerlib.MessageDefinitionSendEmailRequest;
const QueueMORequest = testerlib.QueueMORequest;
const CreateMessageRequest = testerlib.CreateMessageRequest;
const MessageSendRequest = testerlib.MessageSendRequest;

describe("SFMCMessagingController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * queues an MO
     */
    it("should testQueueMO response", function testQueueMOTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let body = baseController.getObjectMapper().mapObject({"subscribers": [{"mobilenumber": "15550001111", "subscriberkey": "subkey_001"}], "shortCode": "64586", "messageText": "GIF"}, 'QueueMORequest');

        controller.createQueueMO(contentType, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * Create a message placeholder in the MarketingCloud
     */
    it("should testCreateMessage response", function testCreateMessageTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let body = baseController.getObjectMapper().mapObject({"messageType": 1, "contentType": 1, "sendIndicator": 1, "status": 1, "startDate": "2014-12-10T14:50:00Z", "sendInitiator": 1, "name": "API Created Message 6", "application": {"id": "5248db1e-cac2-4cc8-a587-cb9875bdbd60", "name": "Public Demo Application"}, "alert": "Alert message to show on device", "sound": "default", "badge": "+1", "contentAvailable": 1, "openDirect": "http://www.url.com/", "keys": [{"key": "locationid", "value": "582"}], "IncludedAudiences": [{"id": "VE1aTk5qeU5FZVNZQlhqanRRdFBBQTo2Mzow"}]}, 'CreateMessageRequest');

        controller.createMessage(contentType, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
