/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateSharedContentImageTypeFromScratchInWSRequest
 */
class CreateSharedContentImageTypeFromScratchInWSRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.message = this.constructor.getValue(obj.message);
        this.description = this.constructor.getValue(obj.description);
        this.assets = this.constructor.getValue(obj.assets);
        this.workspaces = this.constructor.getValue(obj.workspaces);
        this.workspaceId = this.constructor.getValue(obj.workspaceId || obj.workspace_id);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'message', realName: 'message' },
            { name: 'description', realName: 'description' },
            { name: 'assets', realName: 'assets', array: true, type: 'Asset' },
            { name: 'workspaces', realName: 'workspaces', array: true },
            { name: 'workspaceId', realName: 'workspace_id' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateSharedContentImageTypeFromScratchInWSRequest;
