/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateLocationRequest
 */
class CreateLocationRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.location = this.constructor.getValue(obj.location);
        this.description = this.constructor.getValue(obj.description);
        this.center = this.constructor.getValue(obj.center);
        this.radius = this.constructor.getValue(obj.radius);
        this.attributes = this.constructor.getValue(obj.attributes);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'location', realName: 'location' },
            { name: 'description', realName: 'description' },
            { name: 'center', realName: 'center', type: 'Center' },
            { name: 'radius', realName: 'radius' },
            { name: 'attributes', realName: 'attributes', array: true, type: 'Attribute' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateLocationRequest;
