/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateMessageRequest
 */
class CreateMessageRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.messageType = this.constructor.getValue(obj.messageType);
        this.contentType = this.constructor.getValue(obj.contentType);
        this.sendIndicator = this.constructor.getValue(obj.sendIndicator);
        this.status = this.constructor.getValue(obj.status);
        this.startDate = this.constructor.getValue(obj.startDate);
        this.sendInitiator = this.constructor.getValue(obj.sendInitiator);
        this.name = this.constructor.getValue(obj.name);
        this.application = this.constructor.getValue(obj.application);
        this.alert = this.constructor.getValue(obj.alert);
        this.sound = this.constructor.getValue(obj.sound);
        this.badge = this.constructor.getValue(obj.badge);
        this.contentAvailable = this.constructor.getValue(obj.contentAvailable);
        this.openDirect = this.constructor.getValue(obj.openDirect);
        this.keys = this.constructor.getValue(obj.keys);
        this.includedAudiences =
          this.constructor.getValue(obj.includedAudiences
     || obj.IncludedAudiences);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'messageType', realName: 'messageType' },
            { name: 'contentType', realName: 'contentType' },
            { name: 'sendIndicator', realName: 'sendIndicator' },
            { name: 'status', realName: 'status' },
            { name: 'startDate', realName: 'startDate' },
            { name: 'sendInitiator', realName: 'sendInitiator' },
            { name: 'name', realName: 'name' },
            { name: 'application', realName: 'application', type: 'Application' },
            { name: 'alert', realName: 'alert' },
            { name: 'sound', realName: 'sound' },
            { name: 'badge', realName: 'badge' },
            { name: 'contentAvailable', realName: 'contentAvailable' },
            { name: 'openDirect', realName: 'openDirect' },
            { name: 'keys', realName: 'keys', array: true, type: 'Keys52' },
            {
                name: 'includedAudiences',
                realName: 'IncludedAudiences',
                array: true,
                type: 'IncludedAudience',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateMessageRequest;
