/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateContactRequest
 */
class CreateContactRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.contactKey = this.constructor.getValue(obj.contactKey);
        this.contactId = this.constructor.getValue(obj.contactId);
        this.attributeSets = this.constructor.getValue(obj.attributeSets);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'contactKey', realName: 'contactKey' },
            { name: 'contactId', realName: 'contactId' },
            { name: 'attributeSets', realName: 'attributeSets', array: true, type: 'AttributeSet' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateContactRequest;
