/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MessageSendRequest
 */
class MessageSendRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.subscribe = this.constructor.getValue(obj.subscribe || obj.Subscribe);
        this.resubscribe = this.constructor.getValue(obj.resubscribe || obj.Resubscribe);
        this.mobileNumbers = this.constructor.getValue(obj.mobileNumbers);
        this.keyword = this.constructor.getValue(obj.keyword);
        this.override = this.constructor.getValue(obj.override || obj.Override);
        this.contentURL = this.constructor.getValue(obj.contentURL || obj.ContentURL);
        this.messageText = this.constructor.getValue(obj.messageText);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'subscribe', realName: 'Subscribe' },
            { name: 'resubscribe', realName: 'Resubscribe' },
            { name: 'mobileNumbers', realName: 'mobileNumbers', array: true },
            { name: 'keyword', realName: 'keyword' },
            { name: 'override', realName: 'Override' },
            { name: 'contentURL', realName: 'ContentURL' },
            { name: 'messageText', realName: 'messageText' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MessageSendRequest;
