/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of PushSendByMessageIdRequest
 */
class PushSendByMessageIdRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.inclusionListIds =
          this.constructor.getValue(obj.inclusionListIds
     || obj.InclusionListIds);
        this.override = this.constructor.getValue(obj.override || obj.Override);
        this.badge = this.constructor.getValue(obj.badge || obj.Badge);
        this.openDirect = this.constructor.getValue(obj.openDirect || obj.OpenDirect);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'inclusionListIds', realName: 'InclusionListIds', array: true },
            { name: 'override', realName: 'Override' },
            { name: 'badge', realName: 'Badge' },
            { name: 'openDirect', realName: 'OpenDirect' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = PushSendByMessageIdRequest;
