/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of QueueMORequest
 */
class QueueMORequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.subscribers = this.constructor.getValue(obj.subscribers);
        this.shortCode = this.constructor.getValue(obj.shortCode);
        this.messageText = this.constructor.getValue(obj.messageText);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'subscribers', realName: 'subscribers', array: true, type: 'Subscriber' },
            { name: 'shortCode', realName: 'shortCode' },
            { name: 'messageText', realName: 'messageText' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = QueueMORequest;
