/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SubscriberAttributes
 */
class SubscriberAttributes extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.firstName = this.constructor.getValue(obj.firstName || obj['First Name']);
        this.lastName = this.constructor.getValue(obj.lastName || obj['Last Name']);
        this.salutationGender =
          this.constructor.getValue(obj.salutationGender
     || obj['Salutation-Gender']);
        this.billingAddressLine1 =
          this.constructor.getValue(obj.billingAddressLine1
     || obj['Billing Address Line 1']);
        this.billingAddressLine2 =
          this.constructor.getValue(obj.billingAddressLine2
     || obj['Billing Address Line 2']);
        this.billingCity = this.constructor.getValue(obj.billingCity || obj['Billing City']);
        this.billingState = this.constructor.getValue(obj.billingState || obj['Billing State']);
        this.billingZip = this.constructor.getValue(obj.billingZip || obj['Billing Zip']);
        this.phoneNumber = this.constructor.getValue(obj.phoneNumber || obj['Phone Number']);
        this.signUpLocation =
          this.constructor.getValue(obj.signUpLocation
     || obj['SignUp Location']);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'firstName', realName: 'First Name' },
            { name: 'lastName', realName: 'Last Name' },
            { name: 'salutationGender', realName: 'Salutation-Gender' },
            { name: 'billingAddressLine1', realName: 'Billing Address Line 1' },
            { name: 'billingAddressLine2', realName: 'Billing Address Line 2' },
            { name: 'billingCity', realName: 'Billing City' },
            { name: 'billingState', realName: 'Billing State' },
            { name: 'billingZip', realName: 'Billing Zip' },
            { name: 'phoneNumber', realName: 'Phone Number' },
            { name: 'signUpLocation', realName: 'SignUp Location' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SubscriberAttributes;
