/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateTopicKeywordGroupRequest
 */
class UpdateTopicKeywordGroupRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.title = this.constructor.getValue(obj.title);
        this.type = this.constructor.getValue(obj.type);
        this.contains = this.constructor.getValue(obj.contains);
        this.andContains = this.constructor.getValue(obj.andContains);
        this.excludes = this.constructor.getValue(obj.excludes);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'title', realName: 'title' },
            { name: 'type', realName: 'type' },
            { name: 'contains', realName: 'contains', array: true, type: 'Contain' },
            { name: 'andContains', realName: 'andContains', array: true, type: 'AndContain' },
            { name: 'excludes', realName: 'excludes', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UpdateTopicKeywordGroupRequest;
