/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Values
 */
class Values extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.lastLogin = this.constructor.getValue(obj.lastLogin || obj.LastLogin);
        this.isActive = this.constructor.getValue(obj.isActive || obj.IsActive);
        this.firstName = this.constructor.getValue(obj.firstName || obj.FirstName);
        this.followerCount = this.constructor.getValue(obj.followerCount || obj.FollowerCount);
        this.lastName = this.constructor.getValue(obj.lastName || obj.LastName);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'lastLogin', realName: 'LastLogin' },
            { name: 'isActive', realName: 'IsActive' },
            { name: 'firstName', realName: 'FirstName' },
            { name: 'followerCount', realName: 'FollowerCount' },
            { name: 'lastName', realName: 'LastName' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Values;
