/**
 * SalesforceMarketingCloudLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    SERVER_1: 'Server 1',

    /**
     * TODO: Write general description for this element
     */
    SERVER_2: 'Server 2',

    /**
     * TODO: Write general description for this element
     */
    SERVER_3: 'Server 3',

};

module.exports = Servers;
